v3.0.0 (#36)
Major changes
* **Breaking changes** major rewrite of S6 Overlay for v3.0.0.0 - see base image and documentation for more information

Minor changes
* Check whether user exists before trying to create it

Documentation changes
* Updating copyright year to 2022

diff --git a/overlay/etc/bf/init.d/11-user b/overlay/etc/bf/init.d/11-user
--- a/overlay/etc/bf/init.d/11-user
+++ b/overlay/etc/bf/init.d/11-user
@@ -1,43 +1,36 @@
-#!/bin/sh
+#!/command/with-contenv sh
 
 set -euo pipefail
 export BF_E=`basename ${0}`
 
 
 #======================================================================================================================
-# Get vsftpd version.
+# Setup variables.
 #======================================================================================================================
 
-cd /tmp
+[[ -z "${FTPS_USER-}" ]] && bf-error "FTPS_USER is required."
+[[ -z "${FTPS_PASS-}" ]] && bf-error "FTPS_PASS is required."
 
-VERSION=$(cat VSFTPD_BUILD)
-bf-debug "vsftpd version ${VERSION}."
-
-
-#======================================================================================================================
-# Install vsftpd and dependencies.
-#======================================================================================================================
-
-bf-echo "Installing vsftpd v${VERSION}..."
-apk add --no-cache \
-    lftp \
-    openssl \
-    vsftpd=${VERSION}
-bf-done
+UID=${FTPS_UID:-1000}
 
 
 #======================================================================================================================
-# Cleanup.
+# Check whether or not the FTP user already exists.
 #======================================================================================================================
 
-bf-echo "Cleaning up default vsftpd and SSL files."
-rm -rf /etc/vsftpd/* /etc/ssl/private
+USER_EXISTS=`getent passwd ${FTPS_USER} || echo ''`
+if [ -n "${USER_EXISTS}" ] ; then
+    bf-echo "User ${FTPS_USER} already exists."
+    exit 0
+fi
 
-bf-echo "Removing .empty files..."
-rm /files/.empty
-rm /ssl/.empty
 
-bf-echo "Linking SSL directories."
-ln -s /ssl /etc/ssl/private
+#======================================================================================================================
+# Create FTP user.
+#======================================================================================================================
 
-bf-done
+bf-echo "Creating user ${FTPS_USER}..."
+echo -e "${FTPS_PASS}\n${FTPS_PASS}" | adduser -h ${FTPS_FILES} -s /sbin/nologin -u ${UID} ${FTPS_USER}
+
+bf-echo "Ensuring user owns ${FTPS_FILES}..."
+bf-ch -o ${FTPS_USER}:${FTPS_USER} ${FTPS_FILES}
